# Generated by Django 4.2.7 on 2023-11-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mixtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        null=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="my_mixtape/",
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "about",
                    djrichtextfield.models.RichTextField(
                        blank=True, max_length=1000, null=True
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Misc.", "Misc."),
                            ("Rock", "Rock"),
                            ("Pop", "Pop"),
                            ("J-Pop", "J-Pop"),
                            ("K-Pop", "K-Pop"),
                            ("C-Pop", "C-Pop"),
                            ("Latin", "Latin"),
                            ("Hip-Hop", "Hip-Hop"),
                            ("Electronic", "Electronic"),
                            ("R&B", "R&B"),
                            ("Country", "Country"),
                            ("Jazz", "Jazz"),
                            ("Jazz Fusion", "Jazz Fusion"),
                            ("Classical", "Classical"),
                            ("Folk", "Folk"),
                            ("Blues", "Blues"),
                            ("Punk", "Punk"),
                            ("Metal", "Metal"),
                            ("Reggae", "Reggae"),
                            ("Soul", "Soul"),
                            ("Funk", "Funk"),
                            ("Disco", "Disco"),
                            ("Gospel", "Gospel"),
                            ("World", "World"),
                            ("Indie", "Indie"),
                            ("Ambient", "Ambient"),
                            ("Experimental", "Experimental"),
                            ("Soundtrack", "Soundtrack"),
                            ("Holiday", "Holiday"),
                            ("Comedy", "Comedy"),
                            ("Spoken Word", "Spoken Word"),
                            ("Children's", "Children's"),
                            ("Other", "Other"),
                        ],
                        default="Misc.",
                        max_length=32,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist", models.CharField(blank=True, max_length=200, null=True)),
                ("song_link", models.URLField(max_length=500)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Misc.", "Misc."),
                            ("Rock", "Rock"),
                            ("Pop", "Pop"),
                            ("J-Pop", "J-Pop"),
                            ("K-Pop", "K-Pop"),
                            ("C-Pop", "C-Pop"),
                            ("Latin", "Latin"),
                            ("Hip-Hop", "Hip-Hop"),
                            ("Electronic", "Electronic"),
                            ("R&B", "R&B"),
                            ("Country", "Country"),
                            ("Jazz", "Jazz"),
                            ("Jazz Fusion", "Jazz Fusion"),
                            ("Classical", "Classical"),
                            ("Folk", "Folk"),
                            ("Blues", "Blues"),
                            ("Punk", "Punk"),
                            ("Metal", "Metal"),
                            ("Reggae", "Reggae"),
                            ("Soul", "Soul"),
                            ("Funk", "Funk"),
                            ("Disco", "Disco"),
                            ("Gospel", "Gospel"),
                            ("World", "World"),
                            ("Indie", "Indie"),
                            ("Ambient", "Ambient"),
                            ("Experimental", "Experimental"),
                            ("Soundtrack", "Soundtrack"),
                            ("Holiday", "Holiday"),
                            ("Comedy", "Comedy"),
                            ("Spoken Word", "Spoken Word"),
                            ("Children's", "Children's"),
                            ("Other", "Other"),
                        ],
                        default="Misc.",
                        max_length=32,
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now=True)),
                (
                    "mixtape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="my_mixtape.mixtape",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Mixtape_Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mixtape_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mixtape",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mixtapes",
                to="my_mixtape.mixtape_collection",
            ),
        ),
    ]
