# Generated by Django 4.2.7 on 2023-11-25 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_mixtape", "0002_alter_mixtape_genre_alter_track_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mixtape",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mixtapes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Mixtape_Collection",
        ),
    ]
