# Generated by Django 4.2.7 on 2023-12-03 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_mixtape", "0003_alter_mixtape_collection_delete_mixtape_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mixtape",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="placeholder", max_length=255, verbose_name="image"
            ),
        ),
    ]
